/* Autogenerated with kurento-module-creator */

#ifndef __CHANGE_BACKGROUND_IMPL_HPP__
#define __CHANGE_BACKGROUND_IMPL_HPP__

#include "OpenCVFilterImpl.hpp"
#include "ChangeBackground.hpp"
#include <EventHandler.hpp>
#include <boost/property_tree/ptree.hpp>
#include "ChangeBackgroundOpenCVImpl.hpp"

namespace kurento
{
namespace module
{
namespace changebackground
{
class ChangeBackgroundImpl;
} /* changebackground */
} /* module */
} /* kurento */

namespace kurento
{
void Serialize (std::shared_ptr<kurento::module::changebackground::ChangeBackgroundImpl> &object, JsonSerializer &serializer);
} /* kurento */

namespace kurento
{
class MediaPipelineImpl;
} /* kurento */

namespace kurento
{
namespace module
{
namespace changebackground
{

class ChangeBackgroundImpl : public OpenCVFilterImpl, public virtual ChangeBackground, public virtual ChangeBackgroundOpenCVImpl
{

public:

  ChangeBackgroundImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline);

  virtual ~ChangeBackgroundImpl() = default;

  /* Next methods are automatically implemented by code generator */
  virtual bool connect (const std::string &eventType, std::shared_ptr<EventHandler> handler);
  virtual void invoke (std::shared_ptr<MediaObjectImpl> obj,
                       const std::string &methodName, const Json::Value &params,
                       Json::Value &response);

  virtual void Serialize (JsonSerializer &serializer);
  void setImagePath (const std::string &ImagePath);

private:

  class StaticConstructor
  {
  public:
    StaticConstructor();
  };

  static StaticConstructor staticConstructor;

};

} /* changebackground */
} /* module */
} /* kurento */

#endif /*  __CHANGE_BACKGROUND_IMPL_HPP__ */
