/* Autogenerated with kurento-module-creator */

#ifndef __CHANGE_BACKGROUND_OPENCV_IMPL_HPP__
#define __CHANGE_BACKGROUND_OPENCV_IMPL_HPP__

#include <OpenCVProcess.hpp>
#include "ChangeBackground.hpp"
#include <EventHandler.hpp>
#include <opencv2/core.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/opencv.hpp>


namespace kurento
{
namespace module
{
namespace changebackground
{

class ChangeBackgroundOpenCVImpl : public virtual OpenCVProcess
{

public:

  ChangeBackgroundOpenCVImpl ();

  virtual ~ChangeBackgroundOpenCVImpl() = default;

  virtual void process (cv::Mat &mat);

  void setImagePath(char* image_path);
private:
  cv::Mat background;
  cv::VideoWriter video;
};

} /* changebackground */
} /* module */
} /* kurento */

#endif /*  __CHANGE_BACKGROUND_OPENCV_IMPL_HPP__ */
