/* Autogenerated with kurento-module-creator */

#ifndef __CHANGE_BACKGROUND_HPP__
#define __CHANGE_BACKGROUND_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "OpenCVFilter.hpp"

namespace kurento
{
namespace module
{
namespace changebackground
{
class ChangeBackground;
} /* changebackground */
} /* module */
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::module::changebackground::ChangeBackground> &object, JsonSerializer &serializer);
}

namespace kurento
{
class MediaPipeline;
} /* kurento */

namespace kurento
{
namespace module
{
namespace changebackground
{
class ChangeBackground : public virtual OpenCVFilter
{

public:
  ChangeBackground() = default;
  ~ChangeBackground() override = default;


  virtual void setImagePath (const std::string &ImagePath) = 0;

  const std::string &getType() const override;
  const std::string &getQualifiedType() const override;
  const std::string &getModule() const override;
  const std::vector<std::string> &getHierarchy() const override;

  void Serialize(JsonSerializer &serializer) override = 0;

};

} /* changebackground */
} /* module */
} /* kurento */

#endif /*  __CHANGE_BACKGROUND_HPP__ */
